version: "3"
services:
  traefik:
    image: "traefik:latest"
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - GODADDY_EMAIL=itakwygraizak@gmail.com
      - GODADDY_API_KEY=xxx
      - GODADDY_API_SECRET=xxx
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/itakwygraizak/traefik/traefik.yml:/traefik.yml:ro
      - /home/itakwygraizak/traefik/acme.json:/acme.json
      - /home/itakwygraizak/traefik/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.iw4sz.pl`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:BASIC_AUTH_PASSWORD"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.iw4sz.pl`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=godaddy"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=iw4sz.pl"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.iw4sz.pl"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true