version: "3.9"

services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--log.LEVEL=DEBUG"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=kkuba.iwaszkiewicz@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  
  test_node_1:
    build:
      context: ./test_node_1
      dockerfile: Dockerfile
    container_name: test_node_1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test_node_1.rule=Host(`iw4sz.pl`)"
      - "traefik.http.routers.test_node_1.entrypoints=websecure"
      - "traefik.http.routers.test_node_1.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"

  test-node-2:
    build:
      context: ./test_node_2
      dockerfile: Dockerfile
    container_name: test_node_2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test_node_2.rule=Host(`portfolio.iw4sz.pl`)"
      - "traefik.http.routers.test_node_2.entrypoints=websecure"
      - "traefik.http.routers.test_node_2.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"

  test-node-3:
    build:
      context: ./test_node_3
      dockerfile: Dockerfile
    container_name: test_node_3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test_node_3.rule=Host(`services.iw4sz.pl`)"
      - "traefik.http.routers.test_node_3.entrypoints=websecure"
      - "traefik.http.routers.test_node_3.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"